spring.application.name=demo

app.kafka.topic.payments=payments
app.kafka.topic.result=payment-results
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.bootstrap-servers=26.119.121.217:9092
spring.kafka.consumer.group-id=bank-emulator
spring.kafka.consumer.auto-offset-reset=earliest